sudo: required
services:
  - docker

before_install:
  - docker build -t mukilan1600/test_build -f ./client/Dockerfile.dev ./client

script:
  - docker run mukilan1600/test_build npm test -- --watchAll=false

after_success:
  - docker build -t mukilan1600/multi_client ./client
  - docker build -t mukilan1600/multi_worker ./worker
  - docker build -t mukilan1600/multi_server ./server
  - docker build -t mukilan1600/multi_nginx ./nginx

  - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin

  - docker push mukilan1600/multi_client
  - docker push mukilan1600/multi_worker
  - docker push mukilan1600/multi_server
  - docker push mukilan1600/multi_nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-344305196670"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"